equiv_pos = {
    "QB": ["QB"],
    "RB1": ["RB"],
    "RB2": ["RB"],
    "WR1": ["WR"],
    "WR2": ["WR"],
    "TE": ["TE"],
    "W/R": ["RB", "WR"],
    "OL1": ["OT", "T", "G", "C"],
    "OL2": ["OT", "T", "G", "C"],
    "OL3": ["OT", "T", "G", "C"],
    "K": ["K"],
    "DT1": ["DT"],
    "DE1": ["DE"],
    "DE2": ["DE"],
    "MLB1": ["LB"],
    "MLB2": ["LB"],
    "CB1": ["CB"],
    "CB2": ["CB"],
    "S1": ["S", "FS", "SS"],
    "S2": ["S", "FS", "SS"],
    "DST": []
}