# Generated by Django 3.1.4 on 2020-12-27 01:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hello.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='defaultname', max_length=50)),
                ('league_code', models.CharField(default='0000', max_length=10)),
                ('publicly_joinable', models.BooleanField(default=False)),
                ('already_drafted', models.BooleanField(default=False)),
                ('draft_history', models.JSONField(default=hello.models.def_json)),
                ('draft_started_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('draft_order', models.CharField(default='', max_length=1000)),
                ('draft_order_list', models.JSONField(default=hello.models.def_json)),
                ('drafting_player_un', models.CharField(default='', max_length=30)),
                ('creator', models.ForeignKey(default=hello.models.def_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(default='', max_length=40)),
                ('league_code', models.CharField(default='0000', max_length=10)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('total_points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(default='', max_length=40)),
                ('team_name', models.CharField(default='', max_length=40)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('total_points', models.FloatField()),
                ('leagues', models.ManyToManyField(to='hello.League')),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=40)),
                ('league_code', models.CharField(default='0000', max_length=10)),
                ('team_name', models.CharField(default='', max_length=40)),
                ('eliminated', models.BooleanField(default=False)),
                ('pts_rd1', models.FloatField(default=0)),
                ('pts_rd2', models.FloatField(default=0)),
                ('pts_rd3', models.FloatField(default=0)),
                ('pts_rd4', models.FloatField(default=0)),
                ('players', models.JSONField(default=hello.models.def_team, max_length=1000)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.userprofile')),
            ],
        ),
    ]
