# Generated by Django 3.1.4 on 2020-12-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201215_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
