# Generated by Django 3.1.4 on 2020-12-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_user_league_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='defaultname', max_length=50)),
                ('league_code', models.CharField(default='0000', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='league_code',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='league_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.league'),
        ),
    ]
