# Generated by Django 3.1.4 on 2020-12-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_remove_user_league_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='publicly_joinable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='team_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
