# Generated by Django 3.1.4 on 2020-12-20 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0007_auto_20201220_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(default='', max_length=40)),
                ('league_code', models.CharField(default='0000', max_length=10)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('total_points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=40)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('total_points', models.FloatField()),
                ('leagues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.league')),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
