# Generated by Django 3.1.4 on 2020-12-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20201220_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='leagues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.league'),
        ),
    ]
