# Generated by Django 3.1.4 on 2020-12-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20201220_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leagues',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leagues',
            field=models.ManyToManyField(to='hello.League'),
        ),
    ]
