# Generated by Django 3.1.4 on 2020-12-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20201220_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usrname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
