# Generated by Django 3.1.4 on 2020-12-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_userprofile_usrname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=40)),
                ('eliminated', models.BooleanField(default=False)),
                ('pts_rd1', models.FloatField()),
                ('pts_rd2', models.FloatField()),
                ('pts_rd3', models.FloatField()),
                ('pts_rd4', models.FloatField()),
                ('players', models.JSONField(max_length=1000)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.userprofile')),
            ],
        ),
    ]
