# Generated by Django 3.1.4 on 2020-12-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20201223_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='team',
            name='cb1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='cb2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='de1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='de2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='dt',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='flex',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='k',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='mlb1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='mlb2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='ol1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='ol2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='ol3',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='qb',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='rb1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='rb2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='s1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='s2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='te',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='wr1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='wr2',
            field=models.CharField(default='', max_length=40),
        ),
    ]
