# Generated by Django 3.1.4 on 2020-12-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20201223_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='defense',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='league_code',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.JSONField(default={'CB1': '', 'CB2': '', 'DE1': '', 'DE2': '', 'DST': '', 'DT1': '', 'K': '', 'MLB1': '', 'MLB2': '', 'OL1': '', 'OL2': '', 'OL3': '', 'QB': '', 'RB1': '', 'RB2': '', 'S1': '', 'S2': '', 'TE': '', 'W/R': '', 'WR1': '', 'WR2': ''}, max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
