# Generated by Django 3.1.4 on 2020-12-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20201223_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pts_rd1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='pts_rd2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='pts_rd3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='pts_rd4',
            field=models.FloatField(default=0),
        ),
    ]
