# Generated by Django 3.1.4 on 2020-12-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20201223_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='cb1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cb2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='de1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='de2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='team',
            name='flex',
        ),
        migrations.RemoveField(
            model_name='team',
            name='k',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mlb1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mlb2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ol1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ol2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ol3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='qb',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rb1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rb2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='te',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wr1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wr2',
        ),
    ]
