# Generated by Django 3.1.4 on 2020-12-23 01:17

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_auto_20201223_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.JSONField(default=hello.models.def_team, max_length=1000),
        ),
    ]
