# Generated by Django 3.1.4 on 2020-12-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_auto_20201223_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='already_drafted',
            field=models.BooleanField(default=False),
        ),
    ]
