# Generated by Django 3.1.4 on 2020-12-26 01:23

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_league_already_drafted'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draft_history',
            field=models.JSONField(default=hello.models.def_json),
        ),
    ]
