# Generated by Django 3.1.4 on 2020-12-26 19:42

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_auto_20201226_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draft_order',
            field=models.JSONField(default=hello.models.def_json),
        ),
    ]
