# Generated by Django 3.1.4 on 2020-12-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_league_draft_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='draft_order',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
