# Generated by Django 3.1.4 on 2020-12-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_auto_20201226_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='drafting_player_un',
            field=models.CharField(default='', max_length=30),
        ),
    ]
