# Generated by Django 3.1.4 on 2020-12-26 20:29

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_league_drafting_player_un'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draft_order_list',
            field=models.JSONField(default=hello.models.def_json),
        ),
    ]
